#Adding a module in python
import math as m

print("This is a summary in which will show how we can use numbers in python")
print('summary of two integers:')
print(1+2)
print('Summary of two floats:')
print(9.6+5.3)
print('summary of multiple integers and floats together:')
print(1+2.09+3+4.0+5.6+6.1+7.2+8.3+10+11+18.3)
print('Multiplication of numbers:')
print(1*2*3.1*4.2*5.3*6.1*7*8*9)
print("third power of number 8:")
print(8**3)
print('Div results:')
print(8/4)
print("another Divade result:")
print(8/5)
print('----------------------------------------------------')
print('Power 7 and 4:')
print(m.pow(7,4))
print('Sqrt using Math module:')
print(m.sqrt(144))
print('Factorial using math module:')
print(m.factorial(6))
print('log of 64')
print(m.log2(64))
print('\t20/3')
print('Integer multiplication:')
print(20//3)
print('Integer remaining:')
print(29%3)